"""
alerts.py - Security Alert Triage & Remediation Endpoints.

Why this route exists:
Provides SOC analysts and automated incident response tools with endpoints to
filter, review, claim, annotate, and resolve security alerts generated by the ML engine.
"""

from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from ...database.session import get_db
from ...models.alert import AlertSeverity, AlertStatus
from ...schemas.alert import AlertCreate, AlertUpdate, AlertResponse
from ...schemas.common import PaginatedResponse
from ...services.alert_service import alert_service, AlertService
from ...api.dependencies import get_alert_service

router = APIRouter(prefix="/alerts", tags=["Security Alerts & Triage"])


@router.get(
    "",
    response_model=PaginatedResponse[AlertResponse],
    status_code=status.HTTP_200_OK,
    summary="List Security Alerts",
    description="Retrieves a paginated list of security alerts with optional filtering by status and severity.",
)
def list_alerts(
    status: Optional[AlertStatus] = Query(None, description="Filter by alert status (NEW, ACKNOWLEDGED, RESOLVED, etc.)"),
    severity: Optional[AlertSeverity] = Query(None, description="Filter by severity level (LOW, MEDIUM, HIGH, CRITICAL)"),
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(50, ge=1, le=200, description="Items per page"),
    db: Session = Depends(get_db),
    svc: AlertService = Depends(get_alert_service),
) -> PaginatedResponse[AlertResponse]:
    """List security alerts with filters."""
    skip = (page - 1) * page_size
    items, total = svc.get_alerts(
        db=db, status=status, severity=severity, skip=skip, limit=page_size
    )

    return PaginatedResponse[AlertResponse](
        total=total,
        page=page,
        page_size=page_size,
        items=[AlertResponse.model_validate(i) for i in items],
    )


@router.get(
    "/{alert_id}",
    response_model=AlertResponse,
    status_code=status.HTTP_200_OK,
    summary="Get Alert Details",
    description="Retrieves full details for a specific alert including associated network telemetry.",
)
def get_alert(
    alert_id: int,
    db: Session = Depends(get_db),
    svc: AlertService = Depends(get_alert_service),
) -> AlertResponse:
    """Fetch single alert by ID."""
    alert = svc.get_alert_by_id(db=db, alert_id=alert_id)
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert #{alert_id} not found.",
        )
    return AlertResponse.model_validate(alert)


@router.post(
    "",
    response_model=AlertResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create Manual Alert",
    description="Allows SOC analysts or external detection rules to manually create a security alert.",
)
def create_alert(
    alert_in: AlertCreate,
    db: Session = Depends(get_db),
    svc: AlertService = Depends(get_alert_service),
) -> AlertResponse:
    """Create a security alert."""
    alert = svc.create_alert(db=db, alert_in=alert_in)
    return AlertResponse.model_validate(alert)


@router.patch(
    "/{alert_id}",
    response_model=AlertResponse,
    status_code=status.HTTP_200_OK,
    summary="Update Alert Status or Assignment",
    description="Updates the investigation state, assignee, notes, or severity of an existing alert.",
)
def update_alert(
    alert_id: int,
    alert_in: AlertUpdate,
    db: Session = Depends(get_db),
    svc: AlertService = Depends(get_alert_service),
) -> AlertResponse:
    """Update alert metadata or status."""
    alert = svc.update_alert(db=db, alert_id=alert_id, alert_update=alert_in)
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert #{alert_id} not found.",
        )
    return AlertResponse.model_validate(alert)
